name: 'Download Latest Release Zip'
description: 'Downloads the latest release zip from another repository for use in other actions'
branding:
  icon: 'download'
  color: 'gray-dark'
inputs:
  owner:
    description: 'The Github user or organization that owns the repository'
    required: true
  repo:
    description: 'The repository name'
    required: true
  downloadPath:
    description: 'Path where the zip needs to be save. Should only be directories and not end in a filename'
    required: true
outputs:
  filename:
    description: 'name of the downloaded zip file'
runs:
  using: 'node12'
  main: 'dist/index.js'
